version: '3.0'
name: todosapp
services:
  todosapi:
    container_name: todosapi
    build: .
    image: brventura/todos-api:1.0.0
    ports:
      - 5000:5000
    expose:
      - 5000
    env_file:
      - path: ./.env
        required: true
    depends_on: 
      - todosdb
    restart: always
  todosdb:
    container_name: todosdb
    image: postgres
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - 5432:5432